### ISSUE TITLE
Add support for NVDA 2024.1 changes

### ISSUE THREAD

**Issue by josephsl** [ChrisDuffley/stationPlaylist#161] opened 2023-12-22 13:58 UTC
Hi,

NVDA 2024.1 beta 1 was released on December 18, 2023. As 2024.1 is compatibility breaking release, I advise preparing SPL add-on to at least declare 2024.1 as last tested version.

Other things to note:

* Track time commands may need to be adjusted to take simple review mode changes into accunt (disabled GUI controls are shown in simple review mode in 2024.1).
* Let's think about supporting speech on demand mode for some SPL add-on commands.

Thanks.

**Comment by ChrisDuffley** [comment] 2023-12-22 14:31
Thank you @josephsl, you actually have saved me some time by doing this issue for me! :) I had planned on doing an issue myself but I will consider a PR which will close this one.

I must say here, and will admit this publicly: I'm still quite new to Python and NVDA source code. I've however read the Add-On Developer Guide several times as well as the Technical Overview doc from NVAccess (I may read that one again actually for a better understanding of that) and am also looking at the NVDA repo quite a bit, so I knew in a way this was coming, just not the timeline of it.

As part of my testing with 2024.1, I've noticed (which is an easy fix) that one of the GUI arguments (the first one) needs to be now an int, not a float.

I have also noticed though that speech on demand seems easy to implement, but you had remarked on the Add-Ons list it wouldn't be as easy. What do you suggest as the best approach in order for the ui.message instances to work with on-demand while maintaining compatibility with 2023.3? I had thought about an if/elif/else but didn't know of a more cleaner way for this to be written. I did also see a try/except function but didn't know how that would turn out either.

Thank you for your assistance and advice in this transition. I'm sorry if this causes you any inconvenience, but I will definitely see this as a learning experience for not just here but in general development. if you feel this must continue privately, feel free to email me, either at christophernduffley@gmail.com or nvda@chrisduffley.com.

Thanks!
Chris

**Comment by josephsl** [comment] 2023-12-22 14:58
Hi,
For float to int conversion, this is caused by wxPython 4.2.x. I need the exact log fragment that causes this so we can investigate.

Speech on demand: one backward compatible way of doing it is:

speechOnDemand = {"speechOnDemand": True} if versionInfo.version_year >= 2024 else {}

The biggest worry is compatibility with SPL Assistant/Controller layer commands. If it works, then we can declare that speech on demand is supported in many SPL add-on commands.

Here's the timeline I propose:

* This weekend or around New Year's weekend: release SPL add-on 24.01 to incorporate localization updates since May 2023. This I can do, and doing so also allows us to get feedback through add-on store (creation of add-on review link).
* At the same time: release a development build of the add-on on add-on store to test 2024.1 changes, at least float to int conversion.
* When 2024.1 RC is released: release a compatible version of SPL add-on.

I hope to send a PR either this weekend or next weekend.

Thanks (especially for maintainig the add-on).

**Comment by ChrisDuffley** [comment] 2023-12-22 15:29
> For float to int conversion, this is caused by wxPython 4.2.x. I need the exact log fragment that causes this so we can investigate.
>
I've seen this from a PR that fixed it from NVDA Core, so I believe I can fix this.
Also, I just realized: We also need to fix compatibility with threading as is_alive is the new syntax in 3.11 as you mentioned a while back (this is in encoders module).
> Speech on demand: one backward compatible way of doing it is:
> 
> speechOnDemand = {"speechOnDemand": True} if versionInfo.version_year >= 2024 else {}
> 
> The biggest worry is compatibility with SPL Assistant/Controller layer commands. If it works, then we can declare that speech on demand is supported in many SPL add-on commands.
>
I can take a look and see if I can implement this. If not, I will let you handle this if I have troubles with it.
> Here's the timeline I propose:
> 
> * This weekend or around New Year's weekend: release SPL add-on 24.01 to incorporate localization updates since May 2023. This I can do, and doing so also allows us to get feedback through add-on store (creation of add-on review link).
>
  * This I've already done locally. I can merge to master and get a release out today, including a gesture change for focusing Studio on connect in Encoders dialog, extremely useful for those managing stations and needing the functionality without accidentally switching to their local machine if they haven't changed the gesture for switching machines (if useing TeleNVDA). The reason for this is because of the priority of gesture lookup as you mentioned in the Add-On Developer Guide, with the goal here to reduce gesture conflicts. Only question: Is this going to mess with configuration settings or is that just a setting saved to config anyway? I should probably make those assignable...? I will wait for your input on this before commiting that particular change just for clarification.
> * At the same time: release a development build of the add-on on add-on store to test 2024.1 changes, at least float to int conversion.
> * When 2024.1 RC is released: release a compatible version of SPL add-on.
>
  * Excellent, this works for me.

> I hope to send a PR either this weekend or next weekend.
You can go ahead with the development version. I can take care of this upcoming stable for localizations (I did not realize there were new ones until now, LOL).

> Thanks (especially for maintaining the add-on).
Not a problem at all!
Chris

**Comment by josephsl** [comment] 2023-12-22 16:15
Hi Chris,

All the ingredients for 24.01 release are in main branch - I have just merged localization updates and pushed it to main a few minutes ago (apologies for not seeing the latest message as I was away from my computer).

Encoder/F11 command: this changes internal encoder config used by NVDA. Users can also change focus to Studio setting from encoder settings (NVDA+Alt+0 if I remember right). I think reassigning it from our side would be better although this means users will need to relearn that command (and this must be documented in the readme).

I advise merging in main first (origin/main0 before adding F11 changes (I have also included sconstruct file changes from add-on template). For threading.is_alive, this can be done safely with 24.01 as it is also available in Python 3.7.

Thanks.

**Comment by josephsl** [comment] 2023-12-22 16:17
Hi,

Threading.is_alive: if talking about threading.isAlive, this is no longer present in SPL add-on source code as I took care of it many months ago.

Thanks.

**Comment by josephsl** [comment] 2023-12-22 16:22
Hi,
Two more things:

1. Do you need help with submitting the upcoming stable version to ad-on store? NV Access may need to approve you as SPL add-on maintainer.
2. I think it would be great if you can make the release announcement across NVDA community (users list, add-ons list, to name a few).
Thanks (do let me know if you need urther help and advice).

**Comment by ChrisDuffley** [comment] 2023-12-22 17:00
@josephsl,
Nope, I actually don't need help with that part - I can do the rest from here. I'll be awaiting the PR for starting with 2024.1 (I started creating a branch called 2024.1_compat for this purpose).

Also, if it isn't is_alive, then it's certainly something else in threading, as the Windows API commands aren't executing in any case when monitoring for an encoder is enabled (I'll report back after further testing but this has been the problem for several runs with the SPL Encoder).

Thanks again for your help!

**Comment by ChrisDuffley** [comment] 2023-12-22 17:10
@josephsl,
Actually, re threading/is_alive: There is a snippet for this here for monitoring:
```
			if self.backgroundMonitor:
				try:
					monitoring = SPLBackgroundMonitorThreads[self.encoderId].is_alive()
				except KeyError:
					monitoring = False
				if not monitoring:
					self.connectStart()
		else:
			SPLBackgroundMonitor.clear()
```
Not sure where the change needs to be, but I do know that it did not work properly with monitoring threads in 2024.1.
Thanks!

**Comment by josephsl** [comment] 2023-12-22 18:21
Hi,

And this worked in 2023.3... Looks like we need to look into connect function (the thread) and figure out why user32.dll::SendMessage didn't work as intended.

Thanks.

**Comment by josephsl** [comment] 2023-12-22 18:25
Hi,

the way I trigger this code path is:

1. Open SPL Encoder.
2. Add at least one encoder.
3. Focus on an encoder and press Control+F11 to turn on background monitor.

When I do this, I do hear connection tone, indicating that the thread is active. When I press Control+F11 again, background monitor stops. If you can hear the connection tone but nothing after the encoder connects, chances are that something odd is happening with the connect monitor (the thread itself, the giant while loop).

Thanks.

**Comment by ChrisDuffley** [comment] 2023-12-22 18:52
@josephsl,
OK, I blame Windows and Studio for it. It's working fine. The first time I had the beta running on a portable (and also now), I could not get it to work. One of those bad computer days I guess...
This has actually happened before even with 2023 and I think I needed to restart for it to work properly. Ah well, I thought it was a real issue but it appears not so.
However, I did see this for the longest time, which makes me wonder if it's the cause of checking to see if a track is playing or not or if the thread truly stops when disconnected: Whenever you connect again with the monitor enabled for the second time (without turning the option off), the connect function refuses to continue. It just says "Connected" and does not continue to play or focus to Studio as set in the Encoder settings. That issue also occurs with the SAM Encoder.
Just an oddity, but if it can't be resolved, no worries. The workaround really is to turn off monitoring to force stop the thread and then turn it on to start the thread again.
Thanks.

**Comment by josephsl** [comment] 2023-12-22 22:41
Hi,

Speech on demand: figured it out - participating SPL Assistant/Controller layer commands must set finish function's speech on demand flag to True. I'm investigating a one-liner solution i.e. just change self.finish script in the app module.

Thanks.

**Closed** 2023-12-27 03:26 UTC
